# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KsUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(731, 620)
        self.centralwidget = QtWidgets.QWidget(Widget)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 731, 609))
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.label_1.setObjectName("label_1")
        self.queryEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.queryEdit.setGeometry(QtCore.QRect(70, 10, 431, 31))
        self.queryEdit.setObjectName("queryEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 8, 93, 35))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 64, 35))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 450, 51, 16))
        self.label_3.setObjectName("label_3")
        self.logTextArea = QtWidgets.QTextBrowser(self.centralwidget)
        self.logTextArea.setGeometry(QtCore.QRect(10, 470, 711, 131))
        self.logTextArea.setObjectName("logTextArea")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 71, 22))
        self.label.setObjectName("label")
        self.depth = QtWidgets.QComboBox(self.centralwidget)
        self.depth.setGeometry(QtCore.QRect(80, 60, 71, 22))
        self.depth.setObjectName("depth")
        self.depth.addItem("")
        self.depth.addItem("")
        self.depth.addItem("")
        self.depth.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 60, 31, 22))
        self.label_4.setObjectName("label_4")
        self.checkBox_C = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_C.setEnabled(True)
        self.checkBox_C.setGeometry(QtCore.QRect(230, 60, 41, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.checkBox_C.setFont(font)
        self.checkBox_C.setStyleSheet("")
        self.checkBox_C.setCheckable(True)
        self.checkBox_C.setChecked(True)
        self.checkBox_C.setObjectName("checkBox_C")
        self.checkBox_D = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_D.setGeometry(QtCore.QRect(270, 60, 41, 22))
        self.checkBox_D.setChecked(True)
        self.checkBox_D.setObjectName("checkBox_D")
        self.checkBox_E = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_E.setGeometry(QtCore.QRect(310, 60, 41, 22))
        self.checkBox_E.setChecked(True)
        self.checkBox_E.setObjectName("checkBox_E")
        self.checkBox_F = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_F.setGeometry(QtCore.QRect(350, 60, 41, 22))
        self.checkBox_F.setChecked(True)
        self.checkBox_F.setObjectName("checkBox_F")
        self.checkBox_G = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_G.setGeometry(QtCore.QRect(390, 60, 41, 22))
        self.checkBox_G.setChecked(True)
        self.checkBox_G.setObjectName("checkBox_G")
        self.checkBox_I = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_I.setGeometry(QtCore.QRect(470, 60, 41, 22))
        self.checkBox_I.setChecked(True)
        self.checkBox_I.setObjectName("checkBox_I")
        self.checkBox_J = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_J.setGeometry(QtCore.QRect(510, 60, 41, 22))
        self.checkBox_J.setChecked(True)
        self.checkBox_J.setObjectName("checkBox_J")
        self.checkBox_K = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_K.setGeometry(QtCore.QRect(550, 60, 41, 22))
        self.checkBox_K.setChecked(True)
        self.checkBox_K.setObjectName("checkBox_K")
        self.checkBox_L = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_L.setGeometry(QtCore.QRect(590, 60, 41, 22))
        self.checkBox_L.setChecked(True)
        self.checkBox_L.setObjectName("checkBox_L")
        self.checkBox_H = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_H.setGeometry(QtCore.QRect(430, 60, 41, 22))
        self.checkBox_H.setChecked(True)
        self.checkBox_H.setObjectName("checkBox_H")
        self.listview_result = QtWidgets.QListView(self.centralwidget)
        self.listview_result.setEnabled(True)
        self.listview_result.setGeometry(QtCore.QRect(15, 121, 701, 311))
        self.listview_result.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listview_result.setObjectName("listview_result")
        self.scan_button = QtWidgets.QPushButton(self.centralwidget)
        self.scan_button.setGeometry(QtCore.QRect(610, 8, 111, 35))
        self.scan_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scan_button.setObjectName("scan_button")
        self.statusbar = QtWidgets.QStatusBar(Widget)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 20))
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(Widget)
        self.depth.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "MainWindow"))
        self.label_1.setText(_translate("Widget", "关键字"))
        self.pushButton.setText(_translate("Widget", "搜索"))
        self.label_2.setText(_translate("Widget", "结果展示"))
        self.label_3.setText(_translate("Widget", "日志"))
        self.label.setText(_translate("Widget", "扫描深度"))
        self.depth.setItemText(0, _translate("Widget", "8"))
        self.depth.setItemText(1, _translate("Widget", "5"))
        self.depth.setItemText(2, _translate("Widget", "3"))
        self.depth.setItemText(3, _translate("Widget", "无限制"))
        self.label_4.setText(_translate("Widget", "盘符"))
        self.checkBox_C.setText(_translate("Widget", "C"))
        self.checkBox_D.setText(_translate("Widget", "D"))
        self.checkBox_E.setText(_translate("Widget", "E"))
        self.checkBox_F.setText(_translate("Widget", "F"))
        self.checkBox_G.setText(_translate("Widget", "G"))
        self.checkBox_I.setText(_translate("Widget", "I"))
        self.checkBox_J.setText(_translate("Widget", "J"))
        self.checkBox_K.setText(_translate("Widget", "K"))
        self.checkBox_L.setText(_translate("Widget", "L"))
        self.checkBox_H.setText(_translate("Widget", "H"))
        self.scan_button.setText(_translate("Widget", "重新扫描磁盘"))
